### ISSUE TITLE
Bad quotes in __done_humanize_duration?

### ISSUE THREAD

**Issue by aselker** [franciscolourenco/done#101] opened 2021-03-02 18:21 UTC
When a long-running process finishes, these messages show up in the terminal:
```
(standard_in) 1: syntax error
(standard_in) 1: syntax error
test: Missing argument at index 2
test: Missing argument at index 2
```
Also, the title of the notification is just "Done in", not e.g. "Done in 20s".

I think the problem is on lines 159 and 160 of `done.fish`, which read:
```
set -l seconds (math --scale=0 "$milliseconds/1000" % 60)
set -l minutes (math --scale=0 "$milliseconds/60000" % 60)
```
Running one of those lines in a terminal fails.  I think Fish doesn't like the %.  If I move the quotes to this...
```
set -l seconds (math --scale=0 "$milliseconds/1000 % 60")
set -l minutes (math --scale=0 "$milliseconds/60000 % 60")
```
...then the error messages go away, and the notification shows the runtime.

**Comment by franciscolourenco** [comment] 2021-03-02 18:59
Hi @aselker, thank you for reporting this. Would you be up for submitting a pull request?

**Comment by franciscolourenco** [comment] 2021-04-05 14:44
Which version of fish are you using? I can't reproduce this issue.

**Comment by aselker** [comment] 2021-04-12 17:23
I updated to Fish 3.2.2, from version 2.something, and the problem seems to be gone.

**Comment by franciscolourenco** [comment] 2021-04-12 18:28
OK, so it seems to depend on the version

**Comment by franciscolourenco** [comment] 2023-09-27 20:57
Closing this as it seems to only be fixed in newer version of fish. Thanks for reporting!

**Closed by franciscolourenco** 2023-09-27 20:57 UTC
Labels: bug, help-welcome, v2.x
