### ISSUE TITLE
Default excluded commands

### ISSUE THREAD

**Issue by BarbzYHOOL** [franciscolourenco/done#37] opened 2018-06-12 21:00 UTC
I suggest to add these commands to the default ignored commands:

    nano vim edit sudoedit ssh top man htop iotop less more

If I find more I'll note them down.

Feel free to discuss them

**Comment by franciscolourenco** [comment] 2018-09-15 18:50
These are commands which are supposed to terminate while your terminal is in the foreground - in which case the script should not send a notification. 

On the other hand, if a ssh session in the background, you might want to know about 
it.

Do you receive a notifications when run these commands?

**Comment by BarbzYHOOL** [comment] 2018-09-17 16:03
Hmm you're right, I don't know how but I received notification with some of these commands but I don't remember how and why

**Comment by ammgws** [comment] 2019-10-12 00:45
Is it safe to close this issue now? I cannot reproduce it either.

**Closed** 2019-10-12 12:44 UTC
Labels: enhancement
